version: '3.3'
services:
  message-broker:
    image: rabbitmq:3.8-management
    hostname: message-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  spots-gateway:
    image: 'spots-gateway:latest'
    hostname: spots-gateway
    build:
      context: .
    container_name: spots-gateway
    ports:
      - 8081:8080
  
  spotservice:
    image: 'spotservice:latest'
    hostname: spotservice
    build:
      context: .
    container_name: spotservice
    ports:
      - 8082:8080